version: '2'
services:
  zabbix-xxl:
    image: monitoringartist/dockbix-xxl:latest
    ports:
      - "${public_port}:80"
      - "${server_port}:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ZS_DBHost=${db_server}
      - ZS_DBUser=${db_user}
      - ZS_DBPassword=${db_password}
      - ZS_DBName=${db_name}
      - ZS_ValueCacheSize=${value_cache_size}M
      - ZS_StartPingers=${pingers}
      - ZS_StartPollers=${pollers}
      - ZS_StartTrappers=${pollers}
      - XXL_searcher=false
